const el=id=>document.getElementById(id);let cases=[];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json'}});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Check the required fields.');return data}
async function refresh(){cases=await api('/cases');const open=cases.filter(c=>!['Resolved','Post-incident review'].includes(c.status));el('metrics').innerHTML=[['Open cases',open.length],['Critical / high',open.filter(c=>['P0','P1'].includes(c.recommendation.severity)).length],['Teams engaged',new Set(open.map(c=>c.recommendation.team)).size],['Human review', '100%']].map(([a,b])=>`<div class="metric"><span>${a}</span><strong>${b}</strong></div>`).join('');render()}
function render(){const selected=cases.filter(c=>!el('filter').value||c.recommendation.severity===el('filter').value);el('queue').innerHTML=selected.length?selected.map(c=>`<button class="case" data-id="${c.id}"><span class="badge ${c.recommendation.severity}">${c.recommendation.severity}</span> <span class="meta">${escape(c.recommendation.category)}</span><strong>${escape(c.title)}</strong><span class="meta">${escape(c.recommendation.team)} · ${escape(c.status)}</span></button>`).join(''):'<p class="muted">No cases yet. Create one or load samples.</p>';document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>detail(b.dataset.id))}
const next={'New':'Triage','Triage':'Investigation','Investigation':'Mitigation','Mitigation':'Customer communication','Customer communication':'Resolved','Resolved':'Post-incident review'};
function detail(id){const c=cases.find(c=>c.id===id);el('detail').classList.remove('hidden');el('detail').innerHTML=`<h2>${escape(c.title)}</h2><p>${escape(c.description)}</p><p><b>Recommended:</b> ${c.recommendation.severity} · ${escape(c.recommendation.team)}</p><p class="muted">Evidence: ${escape(c.recommendation.evidence.join(', ')||'No rule matched; manual triage needed')}. This is a recommendation, subject to human review.</p><h3>Audit trail</h3>${c.events.map(e=>`<p class="meta">${escape(e.at)} · ${escape(e.action)} · ${escape(e.note)}</p>`).join('')}${next[c.status]?`<form id="transition"><label>Review / handoff note<input id="note" required minlength="5" maxlength="1000"></label><button>Move to ${next[c.status]}</button></form>`:''}`;if(next[c.status])el('transition').onsubmit=async e=>{e.preventDefault();try{await api('/cases/'+id+'/status',{method:'PATCH',body:JSON.stringify({status:next[c.status],note:el('note').value})});await refresh();detail(id)}catch(e){el('message').textContent=e.message}}}
el('case-form').onsubmit=async e=>{e.preventDefault();try{const data=Object.fromEntries(new FormData(e.target));const c=await api('/cases',{method:'POST',body:JSON.stringify(data)});e.target.reset();el('message').textContent='Case created. Review the recommendation below.';await refresh();detail(c.id)}catch(e){el('message').textContent=e.message}};
el('filter').onchange=render;el('seed').onclick=async()=>{try{for(const [title,description] of [['Customer data exposure','An unauthorized user disclosed private customer files.'],['API service disruption','Widespread outage: all customers report API timeouts.'],['Duplicate subscription charge','Customer was charged twice and requests a refund.']])await api('/cases',{method:'POST',body:JSON.stringify({title,description})});await refresh()}catch(e){el('message').textContent=e.message}};refresh().catch(e=>el('message').textContent=e.message);
